package by.bsuir.webtech.ilya.logic;

public enum CommandName {
    NO_SUCH_COMMAND,
    REGISTRATION_COMMAND,
    AUTHORIZATION_COMMAND,
    REGISTRATION_PAGE_COMMAND,
    AUTHORIZATION_PAGE_COMMAND,
    VIEW_BOOKS_COMMAND,
    DELETE_BOOK_COMMAND,
    EDIT_BOOK_PAGE_COMMAND,
    BUY_BOOK_COMMAND,
    EDIT_BOOK_COMMAND;
}
